### ISSUE TITLE
how to specify the output file name explicitly

### ISSUE THREAD

**Issue by shimada-development** [skynav/cap2tt#13]
The current option we have, lets us mention the output directory name and then the output file is created in this directory with the same name as input file and extension replaced by .xml.

Is there a possibility to mention the output file name as argument, so that we know where the output will be available and don't have to guess the output file name?

Also, in such a scenario, would it be possible to not have any reliance on output directory at all? This will help us control IO from this library.

**Comment by skynavga** [comment]
See issue #22 for answer.
