### ISSUE TITLE
warnings reported by find bugs

### ISSUE THREAD

**Issue by shimada-development** [skynav/cap2tt#14]
We ran FindBugs on the source and found the following list of errors:
Our build system doesn't accept source files with FindBugs issued warnings/errors.
Could these be fixed?

---

Converter.java:-1, UUF_UNUSED_FIELD, Priority: Normal
    UuF: Unused field: com.skynav.cap2tt.app.Converter$State.configuration
This field is never used.  Consider removing it from the class.

Converter.java:988, DM_DEFAULT_ENCODING, Priority: High
    Dm: Found reliance on default encoding in com.skynav.cap2tt.app.Converter.getShowOutput(): new java.io.PrintWriter(OutputStream)
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.

Converter.java:1113, RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE, Priority: Normal
    RCN: Redundant nullcheck of uriCurrentDirectory, which is known to be non-null in com.skynav.cap2tt.app.Converter.resolve(String)
This method contains a redundant check of a known non-null value against the constant null.

Converter.java:2430, STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCE, Priority: Normal
    STCAL: Call to method of static java.text.DateFormat in com.skynav.cap2tt.app.Converter.getXSDDateString(Date)
As the JavaDoc states, DateFormats are inherently unsafe for multithreaded use. The detector has found a call to an instance of DateFormat that has been obtained via a static field. This looks suspicous.
For more information on this see Sun Bug #6231579 and Sun Bug #6178997.

Converter.java:3005, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$AttributeSpecification.count
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3006, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$AttributeSpecification.minCount
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3007, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$AttributeSpecification.maxCount
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3022, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Attribute.retain
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3366, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Screen.locator
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3602, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.uriString
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3603, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.succeeded
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3605, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.encodingName
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3612, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.errorsExpected
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3613, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.errors
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3614, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.warningsExpected
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

Converter.java:3615, URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD, Priority: Normal
    UrF: Unread public/protected field: com.skynav.cap2tt.app.Converter$Results.warnings
This field is never read.  The field is public or protected, so perhaps it is intended to be used with classes not seen as part of the analysis. If not, consider removing it from the class.

**Comment by shimada-development** [comment]
Addendum: Adding FindBugs plugin with eclipse IDE might be a good idea to catch any future warnings.

**Comment by skynavga** [comment]
Fixed in 8546fa4d55d9f0178ee69a884b0ad66cb5bbcd67. Used .eclipse findbugs plug-in with all categories enabled.
