### ISSUE TITLE
conflict in ttv.jar and ttx.jar

### ISSUE THREAD

**Issue by shinjantiwary** [skynav/cap2tt#3]
Looks like the Method definitions for the following differ in the dependency jars (ttv.jar is a dependency for cap2tt and ttx.jar is a dependency for ttpe):

(1)
boolean isInheritableStyle(javax.xml.namespace.QName qName);
java.lang.String getInitialStyleValue(javax.xml.namespace.QName qName);

Vs

(2)
boolean isInheritableStyle(javax.xml.namespace.QName qName, javax.xml.namespace.QName qName1);
java.lang.String getInitialStyleValue(javax.xml.namespace.QName qName, javax.xml.namespace.QName qName1);

Since we are integrating both the pieces, it is giving rise to conflicts. Would there be a way to make them consistent?

**Comment by skynavga** [comment]
It appears cap2tt.jar was created using a different (older) version of ttv than used in the ttx dependency for ttpe, thus the conflict. One fix is to ensure that same commit of ttv/ttx is used when building both cap2tt and ttpe.

**Comment by skynavga** [comment]
fixed in tag https://github.com/skynav/cap2tt/releases/tag/pre-alpha-2.1

**Comment by shinjantiwary** [comment]
Thanks. I am able to use ttx for both the modules now
