### ISSUE TITLE
output incompatible with ttpe

### ISSUE THREAD

**Issue by shinjantiwary** [skynav/cap2tt#8]
TTPE seems to fail processing the output generated by cap2tt with following error:

[E]:{file:/home/stiwary/Projects/Shimada/GitHub/test/convertedXml/modified/sample-001_gen.xml}:[4,31]:XSD(cvc-complex-type.2.4.a): Invalid content was found starting with element 'ttm:item'. One of '{"http://www.w3.org/ns/ttml#metadata":agent, "http://www.w3.org/ns/ttml#metadata":copyright, "http://www.w3.org/ns/ttml#metadata":desc, "http://www.w3.org/ns/ttml#metadata":title, "http://www.w3.org/ns/ttml":metadata, "http://www.w3.org/ns/ttml#parameter":profile, "http://www.w3.org/ns/ttml":styling, "http://www.w3.org/ns/ttml":layout}' is expected.
[E]:{file:/home/stiwary/Projects/Shimada/GitHub/test/convertedXml/modified/sample-001_gen.xml}:[7,30]:XSD(cvc-complex-type.2.4.a): Invalid content was found starting with element 'initial'. One of '{"http://www.w3.org/ns/ttml#metadata":agent, "http://www.w3.org/ns/ttml#metadata":copyright, "http://www.w3.org/ns/ttml#metadata":desc, "http://www.w3.org/ns/ttml#metadata":title, "http://www.w3.org/ns/ttml":metadata, "http://www.w3.org/ns/ttml":style}' is expected.

When I fix them manually to match whatever we have in "/ttpe-pre-alpha-2.1/tst/resources/com/skynav/ttpe/app", it seems to work.

The generated XML that I have doesn't seem to have the following in the attribute field. I tried modifying the cap2tt.xml (the configuration file), but could not get these parameters in the attribute.

(A)
(1) ttp:version="2"
(2) ttva:model="ttml2"
(3) xmlns:ttva="http://skynav.com/ns/ttv/annotations"
(4) xmlns:ttp="http://www.w3.org/ns/ttml#parameter"

Also there seemed to be a problem with "textEmphasis"
(B)
The generated XML has <tts:textEmphasisStyle="circle"> in a style attribute. Should it be <tts:textEmphasis="circle">?

Without these the ttpe doesn't seem to process the xml file.

I am using the following to run cap2tt:

-d --warn-on all --force-encoding Shift_JIS --output-indent --output-directory <outputDir> <input.cap>

Please let me know if I am missing an argument or should modify the cap2tt.xml.

**Comment by skynavga** [comment]
The configuration file (cap2tt.xml) is a sample, and another configuration can be substituted using the `--config` option. A `--model ttml2` option can be used with TTPE in lieu of marking the model within the document with the `ttva:model` attribute. However, cap2tt definitely needs to output `ttp:version`, for which I'll open a new issue. Perhaps it should also insert the `ttva:model` attribute as well. The `tts:textEmphasis` property is not yet supported by TTPE. See skynav/ttpe#2.

**Comment by shinjantiwary** [comment]
Looks like my comments had xml styling to it and the github doesn't seem to show it :)
Posting (B) part again:

I believe the issue is "tts:textEmphasisStyle" in the Xml. Once I change it to "tts:textEmphasis" ttpe at least goes ahead and processes the xml for rendering.

**Comment by skynavga** [comment]
Ah, right; we decided to change to a shortcut property, tts:textEmphasis. Will open new issue to update this.

**Comment by skynavga** [comment]
Tasking
- [x] #9
- [x] #10
- [x] #11
- [x] #12

**Comment by skynavga** [comment]
All sub-tasks completed.
